### ISSUE TITLE
Inheritance in Golang

### ISSUE THREAD

**Issue by chiengyn** [Nghiait123456/GolangAdvance#1]
In here: [Inheritance](https://github.com/Nghiait123456/GolangAdvance/tree/master/OOP#inheritance-) , you said:
> Golang has a flexible and powerful inheritance approach

I think writing like that would be easy to misunderstand. Go doesn’t have inheritance – instead composition. The implementations may look the same, but the concepts are totally different.

However, [Inheritance Is Evil. Stop Using It](https://codeburst.io/inheritance-is-evil-stop-using-it-6c4f1caf5117). I think that why Go doesn't have inheritance. And I suggest limited use of Inheritance in the real projects in any language if possible.

**Comment by Nghiait123456** [comment]
@chiennguyen196   hi, Thank you very much. In this thread, I do not intend to analyze OOP Golang like pure OOP languages like Java. First, Golang does not have the standard inheritance of pure OOP inheritance, however, Golang does support inheritance in an embeded struct way. However, my writing can be misleading to newcomers, I will correct this in the next commit.(
https://github.com/Nghiait123456/GolangAdvance/commit/dd393f824bc45ad94265605f614bab88b1e66421)

"However, Inheritance Is Evil. Stop Using It. I think that why Go doesn't have inheritance. And I suggest limited use of Inheritance in the real projects in any language if possible."
==> About this quote, link and article, I have also read through it before. You know, a pattern is born, the anti pattern also appears. Regarding my personal and experience, I don't think inheritance is evil :D, the 4 attributes of OOP always have ground and value in any language, the point is to use it at the right time and in the right place.

**Comment by cuonglm** [comment]
FYI, https://go.dev/doc/faq#inheritance

**Comment by Nghiait123456** [comment]
@cuonglm  okla, thank you. Actually I wanted to present a point of view on inheritance through struct embedding but it seems to have caused unnecessary misunderstandings. I also know well that golang does not have direct inheritance, but a comparative perspective. I fixed it in the commit: https://github.com/Nghiait123456/GolangAdvance/commit/c7b489ca1d55ebe79e3320906c2f579c679ae48c

**Comment by Nghiait123456** [comment]
all problem is clear, i will close this issue. If there is any problem, please contribute issue, I will check and discuss it as soon as possible.
